version: '3.8'

services:
  #Nginx Service
  webserver:
    image: nginx:stable-alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "3001:80"
    volumes:
      - ./src:/var/www
      - ./nginx/:/etc/nginx/conf.d/
    depends_on:
      - app
  app:
    build:
      context: .
      dockerfile: php.dockerfile
    image: digitalocean.com/php
    container_name: app
    restart: unless-stopped
    tty: true
    command: >
<<<<<<< HEAD
      /bin/sh -c "composer install && php-fpm"
=======
      /bin/sh -c "composer install
      && php-fpm"
>>>>>>> 62a3cdd8ffe44043f18cfd02291b2aff7b6f68f8
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./src:/var/www
      - ./php/:/usr/local/etc/php/conf.d/
      - ./nginx_logs/:/var/log/  
    ports:
      - '9000:9000'
  flarum:
    build:
      context: .
      dockerfile: flarum.dockerfile 
    container_name: flarum
    command: >
      /bin/sh -c "chmod -R 777 /var/www/
      && apachectl -DFOREGROUND"
    environment:
      - DEBUG=true
      - FORUM_URL=http://localhost

      # Database configuration 
      - DB_HOST=flarummysql
      - DB_NAME=flarum3
      - DB_USER=root
      - DB_PASS=secret
      - DB_PREF=

      # User admin flarum (environment variable for first installation)
      # /!\ admin password must contain at least 8 characters /!\
      - FLARUM_ADMIN_USER=admin
      - FLARUM_ADMIN_PASS=secretsecret
      - FLARUM_ADMIN_MAIL=admin@domain.tld
      - FLARUM_TITLE=Test flarum

    volumes:
      - ./flarum/public:/var/www
    ports:
      - 80:80
    depends_on:
      - flarummysql
  flarummysql:
    image: mysql:5.7.32
    container_name: flarummysql
    ports:
      - 3306:3306
    volumes:
      - ./mysqlFlarum:/var/lib/mysql
    environment:
      MYSQL_DATABASE: flarum3
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
  appmysql:
    image: mysql:5.7.32
    container_name: mysql
    ports:
      - 3307:3306
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: laraveldb
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: appmysql
      PMA_PORT: 3306
  